### ISSUE TITLE
Error 404: The resource 'projects/miner-project-12345' was not found, notFound

### ISSUE THREAD

**Issue by CosmicBones** [mludvig/gcp-ethereum-miner#1]
i'm getting this issue 

Error 404: The resource 'projects/miner-project-12345' was not found, notFound

**Comment by mludvig** [comment]
You have to change it to your own GCP project name obviously. Reopen if you neex help with that.

**Comment by CosmicBones** [comment]
> You have to change it to your own GCP project name obviously. Reopen if you neex help with that.

how do i do that?
